import { localDateStr } from '../utils.js';

export function CalendarTab({c,t,sessions,setSessions,selectedMonth,setSelectedMonth,selectedDay,setSelectedDay,restDaysLog}){
  const days=new Date(selectedMonth.getFullYear(),selectedMonth.getMonth()+1,0).getDate();
  const firstDay=new Date(selectedMonth.getFullYear(),selectedMonth.getMonth(),1).getDay();
  const monthName=selectedMonth.toLocaleDateString("en-GB",{month:"long",year:"numeric"});
  const getDateStr=d=>`${selectedMonth.getFullYear()}-${String(selectedMonth.getMonth()+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`;
  const todayDateStr=localDateStr();
  const getSession=d=>sessions.find(s=>s.date===getDateStr(d));
  const isRest=d=>restDaysLog.includes(getDateStr(d));
  return(<div style={{maxWidth:820}}>
    <p style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:34,fontWeight:900,color:c.textPrimary,marginBottom:18}}>{t.activityCalendar}</p>
    <div className="kb-cal-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:18}}>
      <div style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:18,padding:22}}>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:16}}><button onClick={()=>setSelectedMonth(new Date(selectedMonth.getFullYear(),selectedMonth.getMonth()-1))} style={{background:"none",border:"none",color:c.textSecondary,cursor:"pointer",fontSize:20,padding:"4px 8px"}}>‹</button><p style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:20,fontWeight:800,color:c.textPrimary}}>{monthName}</p><button onClick={()=>setSelectedMonth(new Date(selectedMonth.getFullYear(),selectedMonth.getMonth()+1))} style={{background:"none",border:"none",color:c.textSecondary,cursor:"pointer",fontSize:20,padding:"4px 8px"}}>›</button></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:3,marginBottom:5}}>{["Su","Mo","Tu","We","Th","Fr","Sa"].map(d=><div key={d} style={{textAlign:"center",fontSize:9.5,color:c.textMuted,padding:"2px 0"}}>{d}</div>)}</div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:3}}>
          {Array.from({length:firstDay}).map((_,i)=><div key={`e${i}`}/>)}
          {Array.from({length:days}).map((_,i)=>{const d=i+1;const dStr=getDateStr(d);const isToday=dStr===todayDateStr;const isW=!!getSession(d);const isR=isRest(d);const isSel=selectedDay===d;return(<div key={d} onClick={()=>setSelectedDay(isSel?null:d)} style={{aspectRatio:"1",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:2,borderRadius:7,background:isSel?c.primaryDim:"transparent",cursor:"pointer",border:isToday?`1.5px solid ${c.primary}`:"1px solid transparent",transition:"all 0.15s"}}><span style={{fontSize:11.5,color:isSel?c.primary:isToday?c.primary:c.textPrimary,fontWeight:isToday?700:400}}>{d}</span>{isW&&<div style={{width:4,height:4,borderRadius:"50%",background:c.purple}}/>}{isR&&!isW&&<div style={{width:4,height:4,borderRadius:"50%",background:c.gold}}/>}</div>);})}
        </div>
        <div style={{display:"flex",gap:12,marginTop:12,paddingTop:10,borderTop:`1px solid ${c.border}`}}><div style={{display:"flex",alignItems:"center",gap:5}}><div style={{width:6,height:6,borderRadius:"50%",background:c.purple}}/><span style={{fontSize:10,color:c.textSecondary}}>{t.workout}</span></div><div style={{display:"flex",alignItems:"center",gap:5}}><div style={{width:6,height:6,borderRadius:"50%",background:c.gold}}/><span style={{fontSize:10,color:c.textSecondary}}>{t.rest}</span></div><div style={{display:"flex",alignItems:"center",gap:5}}><div style={{width:10,height:10,borderRadius:2,border:`1.5px solid ${c.primary}`}}/><span style={{fontSize:10,color:c.textSecondary}}>Today</span></div></div>
      </div>
      <div style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:18,padding:22}}>
        {selectedDay&&getSession(selectedDay)?(()=>{const s=getSession(selectedDay);return(<><p style={{fontSize:9.5,color:c.primary,letterSpacing:1.8,textTransform:"uppercase",fontWeight:700,marginBottom:4}}>{getDateStr(selectedDay)}</p><h3 style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:26,fontWeight:900,color:c.textPrimary,marginBottom:3}}>{s.planName}</h3><p style={{fontSize:12,color:c.textSecondary,marginBottom:14}}>{Math.round(s.duration/60)} min · {Math.round(s.totalVolume)} kg volume</p>{s.exercises.map((ex,i)=>(<div key={i} style={{borderBottom:`1px solid ${c.border}`,paddingBottom:9,marginBottom:9}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:12.5,fontWeight:500,color:c.textPrimary}}>{ex.name}</span><span style={{fontSize:11,color:c.textSecondary}}>{ex.sets.length} sets</span></div>{ex.sets.map((s2,j)=><span key={j} style={{fontSize:11,color:c.textMuted,marginRight:9}}>{s2.reps}r @ {s2.weight}kg</span>)}</div>))}<button onClick={()=>{setSessions(p=>p.filter(x=>x.id!==s.id));setSelectedDay(null);}} style={{background:"none",border:"none",color:"#B05050",fontSize:12,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",marginTop:4}}>{t.deleteSession}</button></>);})():(<div style={{height:"100%",minHeight:200,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",color:c.textMuted,gap:10}}><svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round"><rect x="3" y="4" width="18" height="18" rx="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg><p style={{fontSize:12}}>{t.selectDayDetail}</p></div>)}
      </div>
    </div>
  </div>);
}
