import { Ic } from '../icons.jsx';
import { StatCard } from './StatCard.jsx';
import { UpNextWidget } from './UpNextWidget.jsx';
import { calcStreak, localDateStr } from '../utils.js';
import { QUOTES } from '../constants.js';

export function HomeTab({c,t,setTab,running,sessions,restDaysLog,todayActivity,logRestDay,plans,schedule,setSchedule,onSelectPlan}){
  const streak=calcStreak(sessions,restDaysLog);const quote=QUOTES[new Date().getDate()%QUOTES.length];
  const exPRs={};sessions.forEach(s=>s.exercises.forEach(ex=>{const max=Math.max(...ex.sets.map(s2=>parseFloat(s2.weight)||0),0);if(max>0&&(!exPRs[ex.name]||max>exPRs[ex.name]))exPRs[ex.name]=max;}));
  const dayH=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const ds=localDateStr(d);const isW=sessions.some(s=>s.date===ds);const isR=restDaysLog.includes(ds);return{v:isW?100:isR?50:0,d:"SMTWTFS"[d.getDay()],isToday:i===6,isRest:isR};});
  const stats=[{label:t.currentStreak,value:String(streak),unit:t.days,accent:c.primary,info:t.streakHomeInfo},{label:t.totalWorkouts,value:String(sessions.length),unit:t.allTime,accent:c.textPrimary,info:t.totalWorkoutsInfo},{label:t.personalRecords,value:String(Object.keys(exPRs).length),unit:t.set,accent:c.primary,info:t.prsHomeInfo},{label:t.restDays,value:String(restDaysLog.length),unit:t.logged,accent:c.textPrimary,info:t.restDaysInfo}];
  return(<div style={{maxWidth:1020}}>
    <div className="kb-hero" style={{position:"relative",borderRadius:18,overflow:"hidden",marginBottom:20,height:150,background:c.panelHero}}><div style={{position:"absolute",inset:0,backgroundImage:c.grain,opacity:0.8}}/><svg style={{position:"absolute",right:0,top:0,opacity:0.06}} width="280" height="150" viewBox="0 0 280 150"><line x1="280" y1="0" x2="80" y2="150" stroke={c.primary} strokeWidth="1"/><circle cx="220" cy="75" r="55" stroke={c.primary} strokeWidth="0.5" fill="none"/></svg><div style={{position:"absolute",inset:0,padding:"20px 28px",display:"flex",flexDirection:"column",justifyContent:"flex-end"}}><div style={{display:"flex",alignItems:"flex-end",justifyContent:"space-between"}}><div><p className="kb-hero-text" style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:44,fontWeight:900,color:c.textPrimary,lineHeight:0.95}}>{sessions.length===0?"Ready to start":"Good work"}<span style={{color:c.primary}}>.</span></p><p style={{fontSize:12.5,color:c.textSecondary,fontStyle:"italic",marginTop:6}}>"{quote}"</p></div>{running&&<div onClick={()=>setTab("log")} style={{display:"flex",alignItems:"center",gap:8,background:"rgba(0,0,0,0.35)",border:`1px solid ${c.primary}44`,borderRadius:10,padding:"8px 14px",cursor:"pointer",backdropFilter:"blur(8px)"}}><span style={{width:7,height:7,borderRadius:"50%",background:c.primary,animation:"pulse 1.5s infinite"}}/><span style={{fontSize:12.5,color:c.primary,fontWeight:600}}>Active →</span></div>}</div></div></div>
    <div className="kb-home-stats kb-stat4" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:11,marginBottom:16}}>{stats.map(s=><StatCard key={s.label} {...s} c={c}/>)}</div>
    <div className="kb-home-bottom" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1.5fr",gap:14}}>
      <div style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:13,padding:"17px 17px 15px",display:"flex",flexDirection:"column",boxShadow:"0 1px 4px rgba(0,0,0,0.06)"}}>
        <p style={{fontSize:9.5,color:c.textMuted,letterSpacing:1.7,textTransform:"uppercase",fontWeight:700,marginBottom:11}}>{t.quickStart}</p>
        <button onClick={()=>setTab("log")} disabled={todayActivity==="rest"} style={{width:"100%",background:todayActivity==="rest"?c.border:c.primary,color:todayActivity==="rest"?c.textMuted:"#fff",border:"none",borderRadius:9,padding:"11px 14px",fontSize:14,fontWeight:800,fontFamily:"'Barlow Condensed',sans-serif",cursor:todayActivity==="rest"?"not-allowed":"pointer",display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:7,opacity:todayActivity==="rest"?0.5:1,transition:"all 0.2s",boxShadow:todayActivity==="rest"?"none":`0 3px 12px ${c.primary}44`}}><span style={{display:"flex",alignItems:"center",gap:7}}>{Ic.log} {t.logWorkoutBtn}</span></button>
        <button onClick={()=>{if(todayActivity===null){logRestDay();setTab("rest");}}} disabled={todayActivity!==null} style={{width:"100%",background:"transparent",color:todayActivity!==null?c.textMuted:c.textSecondary,border:"none",borderRadius:8,padding:"7px",fontSize:12.5,fontFamily:"'DM Sans',sans-serif",cursor:todayActivity!==null?"not-allowed":"pointer",display:"flex",alignItems:"center",justifyContent:"center",gap:6,opacity:todayActivity!==null?0.35:0.75}}>{Ic.rest} <span>{t.logRestDay}</span></button>
        <div style={{height:1,background:c.border,margin:"13px 0 11px"}}/>
        <p style={{fontSize:9.5,color:c.textMuted,letterSpacing:1.7,textTransform:"uppercase",fontWeight:700,marginBottom:9}}>{t.thisWeek}</p>
        <svg viewBox="0 0 140 52" width="100%"><line x1="0" y1="42" x2="140" y2="42" stroke={c.border} strokeWidth="1"/>{dayH.map(({v,d,isToday,isRest},i)=>{const bh=v*0.36,x=i*20+2;return(<g key={i}><rect x={x} y={42-bh} width={16} height={bh||1} rx="2.5" fill={v===0?c.border:isRest?c.purple:isToday?c.primary:`${c.primary}60`}/><text x={x+8} y="50" textAnchor="middle" fontSize="8" fill={isToday?c.primary:c.textMuted} fontFamily="DM Sans">{d}</text></g>);})}</svg>
      </div>
      <UpNextWidget c={c} t={t} plans={plans} schedule={schedule} setSchedule={setSchedule} onSelectPlan={onSelectPlan}/>
      <div style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:13,padding:"17px",boxShadow:"0 1px 4px rgba(0,0,0,0.06)"}}>
        <p style={{fontSize:9.5,color:c.textMuted,letterSpacing:1.7,textTransform:"uppercase",fontWeight:700,marginBottom:11}}>{t.recentActivity}</p>
        {sessions.length===0?(<div style={{padding:"24px 0",textAlign:"center"}}><p style={{fontSize:13,color:c.textMuted,marginBottom:4}}>{t.noWorkoutsYet}</p><p style={{fontSize:11.5,color:c.textMuted}}>{t.startFirst}</p></div>):(<div style={{display:"flex",flexDirection:"column",gap:6}}>{sessions.slice(0,5).map((s,i)=>(<div key={s.id} style={{display:"flex",alignItems:"center",gap:9,padding:"8px 10px",background:c.bg,borderRadius:9,border:`1px solid ${c.border}`,transition:"border-color 0.15s"}}><div style={{width:26,height:26,borderRadius:6,background:c.primaryDim,display:"flex",alignItems:"center",justifyContent:"center",color:c.primary,flexShrink:0}}>{Ic.log}</div><div style={{flex:1,minWidth:0}}><p style={{fontSize:12,fontWeight:500,color:c.textPrimary,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{s.planName}</p><p style={{fontSize:10,color:c.textSecondary}}>{i===0?"Today":s.date} · {Math.round(s.duration/60)} min</p></div><span style={{fontSize:10,color:c.textMuted,flexShrink:0}}>{s.exercises.reduce((a,e)=>a+e.sets.length,0)}s</span></div>))}</div>)}
      </div>
    </div>
  </div>);
}
