import { useState, useEffect } from 'react';
import { Ic } from '../icons.jsx';

export function LogTab({c,t,activeWorkout,setActiveWorkout,plans,onStart,checkSet,updateSet,finishWorkout,allSetsDone,formatTime,fmtMin,todayActivity,defaultPlanId}){
  const [selPlanId,setSelPlanId]=useState(defaultPlanId||plans[0]?.id);
  useEffect(()=>{if(defaultPlanId)setSelPlanId(defaultPlanId);},[defaultPlanId]);
  if(!activeWorkout){
    if(todayActivity==="rest")return(<div style={{maxWidth:460,margin:"60px auto",textAlign:"center"}}><div style={{fontSize:48,marginBottom:16}}>🌙</div><p style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:30,fontWeight:900,color:c.textPrimary,marginBottom:8}}>{t.restBlockedMsg}</p><p style={{fontSize:14,color:c.textSecondary}}>{t.restBlockedSub}</p></div>);
    return(<div style={{maxWidth:500,margin:"56px auto",textAlign:"center"}}><p style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:34,fontWeight:900,color:c.textPrimary,marginBottom:6}}>{t.logWorkout}</p><p style={{fontSize:13,color:c.textSecondary,marginBottom:24}}>{t.selectPlan}</p><div style={{display:"flex",flexDirection:"column",gap:9,marginBottom:20}}>{plans.map(p=>(<div key={p.id} onClick={()=>setSelPlanId(p.id)} style={{display:"flex",alignItems:"center",justifyContent:"space-between",background:c.card,border:`1.5px solid ${selPlanId===p.id?c.primary:c.border}`,borderRadius:12,padding:"13px 16px",cursor:"pointer",transition:"all 0.15s",boxShadow:selPlanId===p.id?`0 0 0 3px ${c.primary}22`:"none"}}><div><p style={{fontSize:14,fontWeight:600,color:c.textPrimary}}>{p.name}</p><p style={{fontSize:11.5,color:c.textSecondary}}>{p.exercises.length} {t.exercises}</p></div><div style={{width:20,height:20,borderRadius:"50%",border:`2px solid ${selPlanId===p.id?c.primary:c.border}`,background:selPlanId===p.id?c.primary:"transparent",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",flexShrink:0,transition:"all 0.15s"}}>{selPlanId===p.id&&Ic.check}</div></div>))}</div><button onClick={()=>{const p=plans.find(x=>x.id===selPlanId);if(p)onStart(p);}} style={{background:c.primary,color:"#fff",border:"none",borderRadius:12,padding:"13px 42px",fontSize:15,fontWeight:900,fontFamily:"'Barlow Condensed',sans-serif",cursor:"pointer",boxShadow:`0 4px 16px ${c.primary}44`}}>▶ {t.startWorkout}</button></div>);
  }
  const w=activeWorkout;
  const totalSets=w.exercises.reduce((a,e)=>a+e.sets.length,0);const doneSets=w.exercises.reduce((a,e)=>a+e.sets.filter(s=>s.done).length,0);const progress=(doneSets/totalSets)*100;
  const togglePause=()=>setActiveWorkout(p=>({...p,paused:!p.paused}));
  const warmupProgress=Math.min(100,(w.elapsed/w.warmup.target)*100);const warmupDone=w.elapsed>=w.warmup.target;
  return(<div className="kb-log-grid" style={{maxWidth:1100,margin:"0 auto",display:"grid",gridTemplateColumns:"1fr 280px",gap:20}}>
    <div>
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:14}}>
        <div><p style={{fontSize:10,color:c.primary,letterSpacing:1.8,textTransform:"uppercase",fontWeight:700,marginBottom:3}}>{t.activeSession}</p><h2 style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:28,fontWeight:900,color:c.textPrimary}}>{w.planName}</h2></div>
        <div style={{display:"flex",gap:7}}>
          <button onClick={togglePause} style={{background:w.paused?c.primaryDim:"transparent",color:w.paused?c.primary:c.textSecondary,border:`1px solid ${w.paused?c.primary+"55":c.border}`,borderRadius:8,padding:"6px 12px",fontSize:12,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",display:"flex",alignItems:"center",gap:5}}>{w.paused?<>{Ic.play} {t.resume}</>:<>{Ic.pause} {t.pause}</>}</button>
          <button onClick={()=>setActiveWorkout(null)} style={{background:"none",border:`1px solid ${c.border}`,color:c.textSecondary,borderRadius:8,padding:"6px 11px",fontSize:12,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>✕ {t.cancelWorkout}</button>
        </div>
      </div>
      {w.warmup.enabled&&!w.warmup.done&&(
        <div style={{background:c.card,border:`1px solid ${warmupDone?c.success+"55":c.primary+"33"}`,borderLeft:`3px solid ${warmupDone?c.success:c.primary}`,borderRadius:"0 12px 12px 0",padding:"13px 16px",marginBottom:11}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:9}}>
            <div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:13,fontWeight:600,color:warmupDone?c.success:c.textPrimary}}>🔥 {t.warmup}</span>{warmupDone&&<span style={{fontSize:9,background:c.successDim,color:c.success,padding:"2px 7px",borderRadius:20,fontWeight:700}}>TARGET REACHED</span>}</div>
            <div style={{display:"flex",gap:8,alignItems:"center"}}>
              <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:14,color:warmupDone?c.success:c.primary,fontWeight:600}}>{fmtMin(w.elapsed)}</span>
              <span style={{fontSize:11,color:c.textMuted}}>/</span>
              <div style={{display:"flex",alignItems:"center",gap:4}}>
                <input type="number" min="1" max="60" value={Math.max(1,Math.round(w.warmup.target/60))} onChange={e=>setActiveWorkout(p=>({...p,warmup:{...p.warmup,target:Math.max(60,(parseInt(e.target.value)||1)*60)}}))} style={{width:36,background:c.inputBg,border:`1px solid ${c.borderMid}`,borderRadius:6,padding:"3px 5px",color:c.textPrimary,fontSize:12,fontFamily:"'JetBrains Mono',monospace",textAlign:"center"}}/>
                <span style={{fontSize:11,color:c.textMuted}}>min</span>
              </div>
              <button onClick={()=>setActiveWorkout(p=>({...p,warmup:{...p.warmup,done:true}}))} style={{background:warmupDone?c.success:c.primary,color:"#fff",border:"none",borderRadius:7,padding:"5px 13px",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",display:"flex",alignItems:"center",gap:5}}>{Ic.check} Done</button>
            </div>
          </div>
          <div style={{height:4,background:c.border,borderRadius:2}}><div style={{height:"100%",width:`${warmupProgress}%`,background:warmupDone?c.success:c.primary,borderRadius:2,transition:"width 1s linear"}}/></div>
        </div>
      )}
      <div style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:11,padding:"12px 15px",marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:12,fontWeight:600,color:c.textPrimary}}>{t.overallProgress}</span><span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:12,color:c.textSecondary}}>{doneSets}/{totalSets} {t.setsLabel}</span></div><div style={{height:5,background:c.border,borderRadius:3}}><div style={{height:"100%",width:`${progress}%`,background:doneSets===totalSets?c.success:c.primary,borderRadius:3,transition:"width 0.4s"}}/></div></div>
      {w.exercises.map((ex,exIdx)=>{const allDone=ex.sets.every(s=>s.done);const isActive=exIdx===w.currentExIdx&&!allDone;const isResting=w.restTimer&&w.restTimer.exIdx===exIdx;
        return(<div key={ex.id} style={{background:isActive?c.primaryDim:allDone?c.successDim:c.card,border:`1.5px solid ${isActive?c.primary:allDone?c.success:c.border}`,borderLeft:`3px solid ${isActive?c.primary:allDone?c.success:c.border}`,borderRadius:13,padding:"13px 15px",marginBottom:8,transition:"all 0.2s"}}>
          <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:allDone?0:10}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:16,fontWeight:700,color:isActive?c.primary:allDone?c.success:c.textSecondary}}>{ex.name}</span>{isActive&&<span style={{fontSize:9,background:c.primaryDim,color:c.primary,padding:"2px 7px",borderRadius:20,fontWeight:800,letterSpacing:1,border:`1px solid ${c.primary}33`}}>ACTIVE</span>}{allDone&&<span style={{fontSize:9,background:c.successDim,color:c.success,padding:"2px 7px",borderRadius:20,fontWeight:800}}>DONE ✓</span>}</div><span style={{fontSize:11,color:c.textMuted}}>{ex.sets.filter(s=>s.done).length}/{ex.sets.length}</span></div>
          {!allDone&&(<div style={{display:"flex",flexDirection:"column",gap:7}}>{ex.sets.map((s,si)=>(<div key={si} style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:10,color:c.textMuted,width:18,textAlign:"right",flexShrink:0}}>S{si+1}</span><input type="number" value={s.reps} onChange={e=>updateSet(exIdx,si,"reps",e.target.value)} disabled={s.done} style={{width:50,background:s.done?c.border:c.inputBg,border:`1px solid ${s.done?c.border:c.borderMid}`,borderRadius:6,padding:"6px 7px",color:c.textPrimary,fontSize:12,textAlign:"center",fontFamily:"'JetBrains Mono',monospace",opacity:s.done?0.4:1}}/><span style={{fontSize:10,color:c.textMuted}}>{t.repsLabel}</span><input type="number" value={s.weight} onChange={e=>updateSet(exIdx,si,"weight",e.target.value)} disabled={s.done} placeholder="0" style={{width:56,background:s.done?c.border:c.inputBg,border:`1px solid ${s.done?c.border:c.borderMid}`,borderRadius:6,padding:"6px 7px",color:c.textPrimary,fontSize:12,textAlign:"center",fontFamily:"'JetBrains Mono',monospace",opacity:s.done?0.4:1}}/><span style={{fontSize:10,color:c.textMuted}}>{t.kgLabel}</span><button type="button" onClick={()=>checkSet(exIdx,si)} disabled={s.done} style={{width:32,height:32,borderRadius:8,border:`2px solid ${s.done?c.success:c.primary}`,background:s.done?c.success:c.primaryDim,cursor:s.done?"default":"pointer",display:"flex",alignItems:"center",justifyContent:"center",color:s.done?"#fff":c.primary,transition:"all 0.15s",flexShrink:0,padding:0}}>{s.done&&Ic.check}</button></div>))}
          {isResting&&(<div style={{marginTop:7,background:c.bg,borderRadius:9,padding:"9px 12px",border:`1px solid ${c.gold}44`,animation:"restPulse 2s infinite"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:5}}><span style={{fontSize:12,color:c.gold,fontWeight:600}}>⏱ {t.restTimer}{w.paused?" (paused)":""}</span><span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:14,color:c.gold,fontWeight:600}}>{fmtMin(w.restTimer.remaining)}</span><button onClick={()=>setActiveWorkout(p=>({...p,restTimer:null}))} style={{background:"none",border:`1px solid ${c.border}`,color:c.textSecondary,borderRadius:6,padding:"3px 9px",fontSize:11,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>{t.skip}</button></div><div style={{height:4,background:c.border,borderRadius:2}}><div style={{height:"100%",width:`${(w.restTimer.remaining/w.restTimer.total)*100}%`,background:c.gold,borderRadius:2,transition:"width 1s linear"}}/></div></div>)}
          </div>)}
        </div>);})}
      <button onClick={finishWorkout} disabled={!allSetsDone} style={{width:"100%",background:allSetsDone?c.primary:"transparent",color:allSetsDone?"#fff":c.textMuted,border:`1.5px solid ${allSetsDone?c.primary:c.border}`,borderRadius:12,padding:"13px",fontSize:15,fontWeight:900,fontFamily:"'Barlow Condensed',sans-serif",cursor:allSetsDone?"pointer":"not-allowed",marginTop:5,transition:"all 0.3s",boxShadow:allSetsDone?`0 4px 16px ${c.primary}44`:"none"}}>{allSetsDone?"✓ ":""}{t.finishWorkout}</button>
    </div>
    <div style={{display:"flex",flexDirection:"column",gap:11}}>
      <div style={{background:c.card,border:`1px solid ${w.paused?c.gold+"44":c.border}`,borderRadius:16,padding:"20px 18px",textAlign:"center",transition:"border-color 0.3s"}}>
        <p style={{fontSize:9.5,color:c.textSecondary,letterSpacing:1.8,textTransform:"uppercase",marginBottom:11}}>Session Time</p>
        <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:40,fontWeight:500,color:w.paused?c.gold:c.textPrimary,letterSpacing:2,marginBottom:4,transition:"color 0.3s"}}>{formatTime(w.elapsed)}</div>
        {w.paused&&<p style={{fontSize:10,color:c.gold,letterSpacing:2,fontWeight:600,marginBottom:8}}>⏸ PAUSED</p>}
        <p style={{fontSize:11,color:c.textMuted,marginBottom:14}}>{doneSets} / {totalSets} sets</p>
        <div style={{height:4,background:c.border,borderRadius:2}}><div style={{height:"100%",width:`${progress}%`,background:c.primary,borderRadius:2}}/></div>
        <button onClick={togglePause} style={{marginTop:14,width:"100%",background:w.paused?c.primary:c.primaryDim,color:w.paused?"#fff":c.primary,border:`1px solid ${c.primary}44`,borderRadius:9,padding:"9px",fontSize:13,fontWeight:600,fontFamily:"'DM Sans',sans-serif",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",gap:6,transition:"all 0.18s"}}>{w.paused?<>{Ic.play} {t.resume}</>:<>{Ic.pause} {t.pause}</>}</button>
      </div>
      <div style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:13,padding:"14px 16px"}}><p style={{fontSize:9.5,color:c.textSecondary,letterSpacing:1.8,textTransform:"uppercase",marginBottom:10}}>Exercises</p>{w.exercises.map((ex,i)=>{const done=ex.sets.every(s=>s.done);const active=i===w.currentExIdx&&!done;return(<div key={i} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:i<w.exercises.length-1?`1px solid ${c.border}`:"none"}}><span style={{fontSize:12,color:active?c.primary:done?c.success:c.textSecondary}}>{ex.name}</span><span style={{fontSize:11,color:c.textMuted,fontFamily:"'JetBrains Mono',monospace"}}>{ex.sets.filter(s=>s.done).length}/{ex.sets.length}</span></div>);})}</div>
    </div>
  </div>);
}
