import { useState } from 'react';
import { Ic } from '../icons.jsx';
import { InfoPanel } from './InfoPanel.jsx';
import { calcTrainingLoads, detectPlateaus } from '../utils.js';

export function ProgressTab({c,t,sessions,lang}){
  const [section,setSection]=useState("overview");const [openInfo,setOpenInfo]=useState(null);
  const toggleInfo=k=>setOpenInfo(prev=>prev===k?null:k);
  const isRu=lang==="ru";
  const sections=[{id:"overview",label:t.overview},{id:"strength",label:t.strength},{id:"load",label:t.trainingLoad,badge:"LIVE"}];
  const totalVol=sessions.reduce((a,s)=>a+s.totalVolume,0);const avgDur=sessions.length?Math.round(sessions.reduce((a,s)=>a+s.duration,0)/sessions.length/60):0;
  // Weekly average: sessions per week over last 8 weeks
  const now=new Date();let weeksWithData=0;for(let w=0;w<8;w++){const ws=new Date(now);ws.setDate(now.getDate()-(w+1)*7);const we=new Date(now);we.setDate(now.getDate()-w*7);if(sessions.some(s=>new Date(s.date)>=ws&&new Date(s.date)<we))weeksWithData++;}
  const weeklyAvg=weeksWithData>0?(sessions.filter(s=>{const sd=new Date(s.date);const eightWeeksAgo=new Date(now);eightWeeksAgo.setDate(now.getDate()-56);return sd>=eightWeeksAgo;}).length/Math.max(weeksWithData,1)).toFixed(1):"0";

  const exFreq={},exPRs={},exBestSets={};sessions.forEach(s=>s.exercises.forEach(ex=>{exFreq[ex.name]=(exFreq[ex.name]||0)+1;let bestW=0,bestReps=8;ex.sets.forEach(s2=>{const w=parseFloat(s2.weight)||0;if(w>bestW){bestW=w;bestReps=parseInt(s2.reps)||8;}});if(bestW>0){if(!exPRs[ex.name]||bestW>exPRs[ex.name]){exPRs[ex.name]=bestW;exBestSets[ex.name]=bestReps;}}}));
  const freqList=Object.entries(exFreq).sort((a,b)=>b[1]-a[1]).slice(0,8);const medals=["🥇","🥈","🥉"];
  const {atl,ctl,tsb}=calcTrainingLoads(sessions);const plateaus=detectPlateaus(sessions);
  const wkData=Array.from({length:12},(_,i)=>{const wS=new Date(now);wS.setDate(now.getDate()-((11-i)*7));const wE=new Date(wS);wE.setDate(wE.getDate()+7);const ws=sessions.filter(s=>new Date(s.date)>=wS&&new Date(s.date)<wE);return{week:`W${i+1}`,workouts:ws.length,volume:ws.reduce((a,s)=>a+s.totalVolume,0)};});
  const maxVol=Math.max(...wkData.map(w=>w.volume),1);

  // Body part split from plan panel types
  const panelCount={push:0,pull:0,legs:0,upper:0,other:0};
  sessions.forEach(s=>{const planPanel=s.planPanel||"other";if(panelCount[planPanel]!==undefined)panelCount[planPanel]++;else panelCount.other++;});
  const totalPanels=Object.values(panelCount).reduce((a,b)=>a+b,0);
  const panelLabels={push:isRu?"Жим":"Push",pull:isRu?"Тяга":"Pull",legs:isRu?"Ноги":"Legs",upper:isRu?"Верх":"Upper",other:isRu?"Другое":"Other"};
  const panelColors={push:c.primary,pull:c.purple,legs:"#B05050",upper:c.success,other:c.gold};

  const InfoBtn=({k})=>(<button onClick={()=>toggleInfo(k)} style={{background:"none",border:"none",cursor:"pointer",color:openInfo===k?c.primary:c.textMuted,padding:"0 4px",display:"inline-flex",alignItems:"center",marginLeft:4,transition:"color 0.15s"}}>{Ic.info}</button>);
  const Empty=()=>(<div style={{textAlign:"center",padding:"60px 0",color:c.textMuted}}><div style={{fontSize:32,marginBottom:10}}>📊</div><p style={{fontSize:14,marginBottom:5}}>{t.noWorkoutsYet}</p><p style={{fontSize:12}}>{t.startFirst}</p></div>);

  return(<div style={{maxWidth:1200,margin:"0 auto"}}>
    <div style={{display:"flex",alignItems:"flex-end",justifyContent:"space-between",marginBottom:18,flexWrap:"wrap",gap:10}}>
      <div><p style={{fontSize:10,color:c.primary,letterSpacing:1.8,textTransform:"uppercase",fontWeight:700,marginBottom:3}}>{isRu?"Ваш":"Your"}</p><h2 style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:38,fontWeight:900,color:c.textPrimary}}>{t.progressAnalytics}</h2></div>
      <div className="kb-section-tabs" style={{display:"flex",gap:4,background:c.card,border:`1px solid ${c.border}`,borderRadius:11,padding:4}}>{sections.map(s=>(<button key={s.id} onClick={()=>setSection(s.id)} style={{padding:"6px 13px",borderRadius:8,border:"none",fontSize:12,fontWeight:section===s.id?600:400,fontFamily:"'DM Sans',sans-serif",cursor:"pointer",background:section===s.id?c.primary:"transparent",color:section===s.id?"#fff":c.textSecondary,transition:"all 0.18s",display:"flex",alignItems:"center",gap:5,whiteSpace:"nowrap"}}>{s.label}{s.badge&&<span style={{fontSize:8,background:section===s.id?"rgba(255,255,255,0.2)":`${c.success}22`,color:section===s.id?"#fff":c.success,padding:"1px 5px",borderRadius:10,fontWeight:700}}>{s.badge}</span>}</button>))}</div>
    </div>
    {section==="overview"&&(sessions.length===0?<Empty/>:(<>
      <div className="kb-stat4" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:11,marginBottom:14}}>{[{l:isRu?"Объём":"Total Volume",v:totalVol>1000?`${(totalVol/1000).toFixed(1)}t`:`${Math.round(totalVol)}kg`,a:c.primary,k:"volume"},{l:isRu?"Тренировки":"Sessions",v:String(sessions.length),a:c.textPrimary,k:null},{l:isRu?"Ср. длительность":"Avg Duration",v:`${avgDur}${isRu?"м":"m"}`,a:c.textPrimary,k:null},{l:isRu?"В неделю":"Weekly Avg",v:weeklyAvg,a:c.gold,k:"weeklyAvg"}].map(s=>(<div key={s.l} style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:12,padding:"14px 15px",boxShadow:"0 1px 4px rgba(0,0,0,0.06)"}}><div style={{display:"flex",alignItems:"center"}}><p style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:34,fontWeight:900,color:s.a,lineHeight:1}}>{s.v}</p>{s.k&&<InfoBtn k={s.k}/>}</div><p style={{fontSize:11,color:c.textSecondary,marginTop:4}}>{s.l}</p>{s.k&&openInfo===s.k&&<InfoPanel text={s.k==="weeklyAvg"?(isRu?"Среднее количество тренировок в неделю за последние 8 недель.":"Average number of workouts per week over the last 8 weeks."):(t[`${s.k}Info`]||"")} c={c}/>}</div>))}</div>
      <div className="kb-prog-charts" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:14}}>{[{title:t.workoutsPerWeek,key:"workouts",max:Math.max(...wkData.map(w=>w.workouts),1)},{title:t.volumePerWeek,key:"volume",max:maxVol}].map(chart=>(<div key={chart.key} style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:13,padding:"15px 17px"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:11}}><p style={{fontSize:13,fontWeight:600,color:c.textPrimary}}>{chart.title}</p><p style={{fontSize:10,color:c.textMuted}}>{t.last12Weeks}</p></div><svg viewBox={`0 0 ${wkData.length*22} 76`} width="100%"><line x1="0" y1="64" x2={wkData.length*22} y2="64" stroke={c.border} strokeWidth="0.8"/>{wkData.map((w,i)=>{const h=chart.max>0?(w[chart.key]/chart.max)*58:0;const x=i*22+3,isL=i===wkData.length-1;return(<g key={i}><rect x={x} y={64-h} width={16} height={h||1} rx="2" fill={isL?c.primary:i>=wkData.length-4?`${c.primary}60`:`${c.primary}28`}/><text x={x+8} y="74" textAnchor="middle" fontSize="7" fill={isL?c.primary:c.textMuted} fontFamily="DM Sans">{w.week}</text></g>);})}</svg></div>))}</div>
      <div className="kb-prog-freq" style={{display:"grid",gridTemplateColumns:"1.1fr 1fr",gap:12}}>
        <div style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:13,padding:"15px 17px"}}><p style={{fontSize:13,fontWeight:600,color:c.textPrimary,marginBottom:12}}>{t.mostTrained}</p>{freqList.length===0?<p style={{fontSize:12,color:c.textMuted}}>{isRu?"Нет данных.":"No data yet."}</p>:freqList.map(([name,count],i)=>(<div key={name} style={{display:"flex",alignItems:"center",gap:9,marginBottom:8}}><span style={{width:17,fontSize:i<3?13:11,textAlign:"center",flexShrink:0}}>{i<3?medals[i]:i+1}</span><div style={{flex:1}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:2}}><span style={{fontSize:12,color:c.textPrimary}}>{name}</span><span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:10.5,color:c.textMuted}}>{count}×</span></div><div style={{height:3,background:c.border,borderRadius:2}}><div style={{height:"100%",width:`${(count/freqList[0][1])*100}%`,background:i<3?c.primary:`${c.primary}40`,borderRadius:2}}/></div></div></div>))}</div>
        <div style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:13,padding:"15px 17px"}}><div style={{display:"flex",alignItems:"center",marginBottom:11}}><p style={{fontSize:13,fontWeight:600,color:c.textPrimary}}>{t.personalRecordsTitle}</p><InfoBtn k="pr"/></div>{openInfo==="pr"&&<InfoPanel text={t.prInfo} c={c}/>}{Object.keys(exPRs).length===0?<p style={{fontSize:12,color:c.textMuted}}>{isRu?"Нет рекордов.":"No PRs yet."}</p>:Object.entries(exPRs).map(([name,w])=>(<div key={name} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"6px 9px",background:c.bg,borderRadius:8,border:`1px solid ${c.border}`,marginBottom:5}}><div style={{display:"flex",alignItems:"center",gap:6}}><span style={{color:c.primary,opacity:0.7}}>{Ic.trophy}</span><span style={{fontSize:12,color:c.textPrimary}}>{name}</span></div><span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:12.5,color:c.primaryLight,fontWeight:500}}>{w}kg</span></div>))}</div>
      </div>
    </>))}
    {section==="strength"&&(sessions.length===0?<Empty/>:(<div className="kb-prog-charts" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}>
      <div style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:13,padding:"17px 19px"}}><div style={{display:"flex",alignItems:"center",marginBottom:4}}><p style={{fontSize:13,fontWeight:600,color:c.textPrimary}}>{isRu?"Расчётный 1ПМ":"Estimated 1RM"}</p><InfoBtn k="oneRm"/></div>{openInfo==="oneRm"&&<InfoPanel text={t.oneRmInfo} c={c}/>}<p style={{fontSize:10.5,color:c.textMuted,marginBottom:14}}>{isRu?"По лучшему подходу":"Heaviest logged set per exercise"}</p>{Object.keys(exPRs).length===0?<p style={{fontSize:12,color:c.textMuted}}>{isRu?"Запишите тренировки с весами.":"Log workouts with weights to see estimates."}</p>:Object.entries(exPRs).map(([name,maxW])=>{const reps=exBestSets[name]||8;const oneRm=reps<=1?maxW:Math.round(maxW*36/(37-reps));return(<div key={name} style={{display:"flex",justifyContent:"space-between",padding:"8px 0",borderBottom:`1px solid ${c.border}`}}><span style={{fontSize:13,color:c.textPrimary}}>{name}</span><span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:13,color:c.primary,fontWeight:600}}>{oneRm}kg</span></div>);})}</div>
      <div style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:13,padding:"17px 19px"}}><div style={{display:"flex",alignItems:"center",marginBottom:4}}><p style={{fontSize:13,fontWeight:600,color:c.textPrimary}}>{isRu?"Детектор плато":"Plateau Detector"}</p><InfoBtn k="plateau"/></div>{openInfo==="plateau"&&<InfoPanel text={t.plateauInfo} c={c}/>}<p style={{fontSize:10.5,color:c.textMuted,marginBottom:14}}>{isRu?"Последние 21 день vs предыдущие 21":"Last 21 days vs previous 21 days"}</p>{Object.keys(plateaus).length===0?<p style={{fontSize:12,color:c.textMuted}}>{isRu?"Нужно больше данных.":"Need more data to detect plateaus."}</p>:Object.entries(plateaus).map(([name,p])=>(<div key={name} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"8px 0",borderBottom:`1px solid ${c.border}`}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:7,height:7,borderRadius:"50%",background:p.ok?c.success:"#B05050"}}/><span style={{fontSize:12.5,color:c.textPrimary}}>{name}</span></div><span style={{fontSize:11.5,color:p.ok?c.success:"#B05050",fontWeight:600,fontFamily:"'JetBrains Mono',monospace"}}>{p.ok?(p.change!==null?`+${p.change}%`:(isRu?"Новое":"New")):p.change!==null?`${p.change}%`:(isRu?"Плато":"Plateau")}</span></div>))}</div>
    </div>))}
    {section==="load"&&(<div>
      <div className="kb-prog-load" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:11,marginBottom:14}}>{[{l:`${isRu?"Острая нагрузка":"Acute Load"} (ATL)`,v:sessions.length?atl.toFixed(1):"—",sub:isRu?"Индекс усталости (7 дней)":"7-day fatigue index",color:"#B05050",k:"atl"},{l:`${isRu?"Хроническая нагрузка":"Chronic Load"} (CTL)`,v:sessions.length?ctl.toFixed(1):"—",sub:isRu?"Фитнес-база (42 дня)":"42-day fitness base",color:c.primary,k:"ctl"},{l:`${isRu?"Форма":"Form"} (TSB)`,v:sessions.length?(tsb>0?`+${tsb.toFixed(1)}`:tsb.toFixed(1)):"—",sub:tsb>5?(isRu?"Восстановлен ✓":"Recovered ✓"):tsb<-10?(isRu?"Утомлён ⚠":"Fatigued ⚠"):(isRu?"Нейтрально":"Neutral"),color:tsb>5?c.success:tsb<-10?"#B05050":c.gold,k:"tsb"}].map(item=>(<div key={item.l} style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:13,padding:"15px 17px"}}><div style={{display:"flex",alignItems:"center"}}><p style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:36,fontWeight:900,color:item.color,lineHeight:1}}>{item.v}</p><InfoBtn k={item.k}/></div><p style={{fontSize:12.5,fontWeight:600,color:c.textPrimary,marginTop:3}}>{item.l}</p><p style={{fontSize:11,color:c.textSecondary,marginTop:2}}>{item.sub}</p>{openInfo===item.k&&<InfoPanel text={t[`${item.k}Info`]||""} c={c}/>}</div>))}</div>
      <div style={{background:c.card,border:`1px solid ${c.border}`,borderRadius:13,padding:"17px 20px"}}><p style={{fontSize:13,fontWeight:600,color:c.textPrimary,marginBottom:3}}>{isRu?"Рекомендация по разгрузке":"Deload Recommendation"}</p><p style={{fontSize:11,color:c.textMuted,marginBottom:10}}>{isRu?"На основе модели Банистера":"Based on Banister Impulse-Response model"}</p><div style={{background:c.primaryDim,border:`1px solid ${c.primary}33`,borderRadius:10,padding:"12px 14px"}}><p style={{fontSize:12.5,color:c.textSecondary,lineHeight:1.7}}>{sessions.length<6?(isRu?"Запишите хотя бы 6 тренировок для персональной рекомендации.":"Log at least 6 workouts to receive a personalised recommendation."):tsb<-15?(isRu?"⚠️ Высокая усталость. Рассмотрите разгрузку — снизьте объём на 40–50%.":"⚠️ High fatigue detected. Consider a deload — reduce volume 40–50% and intensity 10–20%."):tsb>20?(isRu?"✅ Хорошо восстановлены. Отличная неделя для новых рекордов.":"✅ Well recovered. Great week to push for new PRs."):(isRu?"Хорошее тренировочное окно. Продолжайте текущую программу.":"You're in a good training window. Continue your current programme.")}</p></div></div>
    </div>)}
  </div>);
}
