import { RECOVERY_FACTS } from '../constants.js';

export function RestTab({c,t,todayActivity,onLogRest,onUndoRest,activeWorkout}){
  const fact=RECOVERY_FACTS[new Date().getDate()%RECOVERY_FACTS.length];
  return(<div style={{maxWidth:560}}>
    <div style={{position:"relative",height:160,borderRadius:18,overflow:"hidden",marginBottom:20,background:c.panelRest}}><div style={{position:"absolute",inset:0,backgroundImage:c.grain,opacity:0.8}}/><div style={{position:"absolute",inset:0,padding:"22px 26px",display:"flex",flexDirection:"column",justifyContent:"flex-end"}}><h1 style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:48,fontWeight:900,color:c.textPrimary,lineHeight:0.95}}>{t.restDay}<span style={{color:c.primary}}>.</span></h1><p style={{fontSize:12.5,color:c.textSecondary,marginTop:7}}>Recovery is where the magic happens.</p></div></div>
    {activeWorkout&&(<div style={{background:c.primaryDim,border:`1px solid ${c.primary}33`,borderRadius:12,padding:"15px 18px",marginBottom:16,display:"flex",gap:12,alignItems:"center"}}><span style={{fontSize:22}}>⏱</span><div><p style={{fontSize:14,fontWeight:600,color:c.primary,marginBottom:2}}>{t.workoutActiveMsg}</p><p style={{fontSize:12,color:c.textSecondary}}>{t.workoutActiveSub}</p></div></div>)}
    {todayActivity==="workout"&&!activeWorkout&&(<div style={{background:c.primaryDim,border:`1px solid ${c.primary}33`,borderRadius:12,padding:"15px 18px",marginBottom:16,display:"flex",gap:12,alignItems:"center"}}><span style={{fontSize:22}}>💪</span><div><p style={{fontSize:14,fontWeight:600,color:c.primary,marginBottom:2}}>{t.workoutBlockedMsg}</p><p style={{fontSize:12,color:c.textSecondary}}>{t.workoutBlockedSub}</p></div></div>)}
    <div style={{background:c.card,border:`1px solid ${c.border}`,borderLeft:`3px solid ${c.primary}`,borderRadius:"0 13px 13px 0",padding:"14px 18px",marginBottom:18}}><p style={{fontSize:9.5,color:c.primary,letterSpacing:1.8,textTransform:"uppercase",fontWeight:700,marginBottom:6}}>{t.recoveryInsight}</p><p style={{fontSize:13,color:c.textPrimary,lineHeight:1.8,fontStyle:"italic"}}>"{fact}"</p></div>
    {todayActivity===null&&!activeWorkout&&<button onClick={onLogRest} style={{background:c.primary,color:"#fff",border:"none",borderRadius:13,padding:"13px 38px",fontSize:16,fontWeight:900,fontFamily:"'Barlow Condensed',sans-serif",cursor:"pointer",boxShadow:`0 4px 16px ${c.primary}44`}}>LOG REST DAY</button>}
    {todayActivity==="rest"&&(<div style={{background:c.successDim,border:`1px solid ${c.success}44`,borderRadius:12,padding:"16px 20px"}}><p style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:22,fontWeight:900,color:c.success,marginBottom:3}}>✓ {t.loggedState}</p><p style={{fontSize:13,color:c.textSecondary,marginBottom:12}}>{t.streakSafe}</p><button onClick={onUndoRest} style={{background:"none",border:`1px solid ${c.border}`,color:c.textSecondary,borderRadius:8,padding:"7px 13px",fontSize:12,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>{t.undoRest}</button></div>)}
  </div>);
}
